version: "3.8"

services:
  db:
    image: postgres:15
    container_name: daily_postgres
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
